Add the community contribution and resources
jtr13/cc22mw pull request #5
Opened 2022-11-08 02:13 UTC by shadowfall117

2022-11-09 02:36 UTC, jontse requested changes
Please remove the numbered headings such as "1." "2." below.  The ## and ### will all convert into numbered headings during the rendering.

2022-11-09 02:36 UTC, jontse commented on machine_learning_tutorial.Rmd
> +## 1.Introduction
Please remove the numbered headings such as "1.", here and below.  The ## and ### will all convert into numbered headings during the rendering.

2022-11-10 01:05 UTC, shadowfall117 reviewed
Hello, I have fixed the header issue

2022-11-11 13:32 UTC, shadowfall117 reviewed
Changed header

2022-11-12 03:15 UTC, jontse approved these changes
Thank you for updating and contributing!

2022-11-12 03:17 UTC, merged

2022-11-12 03:17 UTC, jontse commented
Thank you for your contribution!