Add Community Contribution for File Ingestion Tutorial
jtr13/cc22mw pull request #81
Opened 2022-11-25 19:54 UTC by northernsquare

2022-11-27 22:31 UTC, philkim72 commented on file_ingestions.Rmd
> +```{r, include=FALSE}
The first line should start with a single hashtag #, followed by a single whitespace, and then the title.

The second line should be blank, followed by the author name(s).

2022-11-27 22:32 UTC, philkim72 requested changes
The first line should start with a single hashtag #, followed by a single whitespace, and then the title.

The second line should be blank, followed by the author name(s).

2022-12-06 14:14 UTC, philkim72 commented
I requested changes 9 days ago.  Please make chances so that I can merge the pull request.

2022-12-07 01:42 UTC, jtr13 commented
Thanks, I'll handle.

2022-12-10 21:15 UTC, northernsquare commented
@jtr13 Updated formatting accordingly - please review when you get a chance :)

2022-12-11 00:30 UTC, merged

2022-12-11 00:30 UTC, philkim72 commented
thank you for your contribution! :tada: